USE ADMIN_ACADEMIAS
GO
/*
 * EXEC sp_addmessage 50001, 11, 'La nomina ya esta registrada en la carrera'
 * EXEC sp_addmessage 50002, 11, 'No se puede dar de baja el jefe de carrera'
 */
GO
/*
 * Procedimiento para crear carreas
 * EXEC SP_INSERT_CARRERA 'ISC', 'portada.png', 'INGENIERIA EN SITEMAS'
 */
IF OBJECT_ID('SP_INSERT_CARRERA') IS NOT NULL DROP PROC SP_INSERT_CARRERA
GO
CREATE PROC SP_INSERT_CARRERA 
	@CLAVE VARCHAR(255), 
	@FOTO VARCHAR(255), 
	@NOMBRE VARCHAR(255) AS 
	INSERT INTO dbo.CARRERA (clave_carrera, foto_portada, nombre)
	VALUES (@CLAVE, @FOTO, @NOMBRE)
GO
/* 
 * Procedimiento para afiliar las al docente con su carrera
 * EXEC SP_AFILIAR_CARRERA 'ISC', '18130159', 0
 */
IF OBJECT_ID('SP_AFILIAR_CARRERA') IS NOT NULL DROP PROC SP_AFILIAR_CARRERA
GO
CREATE PROC SP_AFILIAR_CARRERA
	@CARREA VARCHAR(255),
	@NOMINA INT,
	@JEFE BIT = 0 AS
	IF NOT EXISTS(SELECT * FROM AFILIADO WHERE nomina = @NOMINA) BEGIN
		IF @JEFE = 1 BEGIN
			UPDATE AFILIADO
			SET JEFE = 0
			WHERE clave_carrera LIKE TRIM(@CARREA)
		END
		INSERT INTO AFILIADO (clave_carrera, nomina, jefe)
		VALUES (@CARREA, @NOMINA, @JEFE)
	END
	ELSE 
		RAISERROR(50001, 11, 1)
GO
/*
 * Procedimiento para cambiar el jefe
 * EXEC SP_CAMBIAR_JEFE '1', 'ISC'
 */
IF OBJECT_ID('SP_CAMBIAR_JEFE') IS NOT NULL DROP PROC SP_CAMBIAR_JEFE
GO
CREATE PROC SP_CAMBIAR_JEFE 
	@NOMINA INT,
	@CLAVE VARCHAR(255) AS
	UPDATE AFILIADO SET jefe = 0 WHERE clave_carrera LIKE TRIM(@CLAVE)
	UPDATE AFILIADO SET JEFE = 1 WHERE clave_carrera LIKE TRIM(@CLAVE) AND nomina = @NOMINA
GO
/*
 * Procedimiento para eliminar un docente de la carrera
 * EXEC SP_ELIMINAR_DOCENTE_CARRERA 1, 'ISC'
 */
IF OBJECT_ID('SP_ELIMINAR_DOCENTE_CARRERA') IS NOT NULL DROP PROC SP_ELIMINAR_DOCENTE_CARRERA
GO
CREATE PROC SP_ELIMINAR_DOCENTE_CARRERA
	@NOMINA INT,
	@CLAVE VARCHAR(255) AS
	IF NOT EXISTS(SELECT * FROM AFILIADO WHERE nomina = @NOMINA AND clave_carrera LIKE TRIM(@CLAVE) AND JEFE = 1 )
		DELETE FROM AFILIADO WHERE nomina = @NOMINA AND clave_carrera LIKE TRIM(@CLAVE)
	ELSE
		RAISERROR(50002, 11, 1)
GO
