USE ADMIN_ACADEMIAS
GO
/*
 * Procedimiento para crear docentes
 * EXEC SP_INSERT_DOCENTE 18130159, 'perfil.png', 'Ya�ez', '18130159', '6442603424'
 */
IF OBJECT_ID('SP_INSERT_DOCENTE') IS NOT NULL DROP PROC SP_INSERT_DOCENTE
GO
CREATE PROC SP_INSERT_DOCENTE 
	@NOMINA INT, 
	@FOTO VARCHAR(255), 
	@NOMBRE VARCHAR(255),
	@CORREO VARCHAR(255),
	@TELEFONO VARCHAR(255) AS
	INSERT INTO dbo.DOCENTE (nomina,  foto,  nombre,  correo,  telefono)
	VALUES(@NOMINA, @FOTO, @NOMBRE, @CORREO, @TELEFONO)
GO
/*
 * Procedimiento para crear academias
 * EXEC SP_INSERT_ACADEMIA 'ISC', 'PORTADA.PNG', 'sistemas'
 */
IF OBJECT_ID('SP_INSERT_ACADEMIA') IS NOT NULL DROP PROC SP_INSERT_ACADEMIA
GO
CREATE PROC SP_INSERT_ACADEMIA 
	@CLAVE VARCHAR(255), 
	@FOTO VARCHAR(255), 
	@NOMBRE VARCHAR(255) AS
	INSERT INTO ACADEMIA (clave_academia, foto_portada, nombre)
	VALUES (@CLAVE, @FOTO, @NOMBRE)
GO 
/*
 * Procedimiento para ligar materias con el docente
 * EXEC SP_LIGAR_MATERIA 18130159, 'METODO NUMERICOS'
 */
IF OBJECT_ID('SP_LIGAR_MATERIA') IS NOT NULL DROP PROC SP_LIGAR_MATERIA
GO 
CREATE PROC SP_LIGAR_MATERIA 
	@NOMINA VARCHAR(255),
	@MATERIA VARCHAR(255) AS
	INSERT INTO MATERIAS (materia, nomina) VALUES (@MATERIA, @NOMINA)
GO